// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uktyewnnkbqjopjeoznp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrdHlld25ua2Jxam9wamVvem5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njc0NzcsImV4cCI6MjA2MjA0MzQ3N30.SyK_AgPVgbyex-s2u4AQG_gAN59AGg7PIw6TseA0GpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);